### ISSUE TITLE
How to reference objects in the schema?

### ISSUE THREAD

**Issue by wzr1337** [wzr1337/rsi.schema#2]
_Originally posted by @sen542 in https://github.com/wzr1337/rsi.schema/pull/1_

Anyway <element> is wrong at this place unless you want to use it as placeholder.

**Comment by wzr1337** [comment]
How about  using a similar notation as for Types:

`"#ref": "medialibrary.videos.videoObject"`

would become

`"#ref": "medialibrary.videosObject"`

similar to 

`"#ref": "addressbook.streetType"`

What do you think @sen542 and @fibric ?

**Comment by wzr1337** [comment]
but, as resources need to be plural form, I would always use the notation in plural form , hence *videosObject* in our case

**Comment by sen542** [comment]
The example above "#ref": "medialibrary.videosObject" looks better. I like that.

**Comment by wzr1337** [comment]
If we now get an up vote from @fibric we can close the issue, as I already pushed some changes in the media rework branch 😉

**Comment by wzr1337** [comment]
no coment in two days.. unusual for @fibric .. this counts as upvote ;)
