### ISSUE TITLE
Change resources to be an array

### ISSUE THREAD

**Issue by wzr1337** [wzr1337/rsi.schema#3]
sen542 commented on dist/$rsi.schema.json in 8d4879a :
I think changing to an array might not be a good idea. Each JSOn schema has to be able to cope with "native" JSON properties like arbitrary order. That's why I'd refrain here from having an array definition.
This comment applies also to other changes when using an array definition just to solve versioning problems in case of arbitrary ordering.

_Originally posted by @sen542 in https://github.com/wzr1337/rsi.schema/pull/1#commitcomment-30891775_

**Comment by ghost** [comment]
Ordering properties for the sake of easing git-diff's can also be achieved by using pre-commit hooks or discipline. Sort locally, then commit.

Just add a folder in `.git` call `hooks` and an executable script named `pre-commit` which ensures sorting. Each time anyone runs `git commit`, `git` automatically runs the script `pre-commit`.

Node.js has an excellent git-hook manager called `husky` - if manual scripting in the `.git/hooks` folder isn't wanted.

**Comment by wzr1337** [comment]
Technically agreed

.. But why do we want to add a process when we can just solve it by a different convention?

By definition, a JSON object properties die not come in any controllable order and any encoder can store them in arbitrary order. From experience, this is inconvenient for the developer, who wants to diff files or just expects his definitions in a particular order.

A general benefit would also be that the Schema would be written very similar to the result you get when exploring the service. It will send you an array of resource objects, not an object..

I find this analogy between definition and exploration very handy

**Comment by ghost** [comment]
> I find this analogy between definition and exploration very handy

In that case, you must convert everything from object to array ;-)

For showcasing I defined `object1` with the property order of `a` then `c` and then `b`. But Firefox instantly replies with the in-memory mapped object representation with the order of `a` then `b` and then `c`.
<img width="1680" alt="screen shot 2018-10-20 at 11 52 12 am" src="https://user-images.githubusercontent.com/623932/47254167-9cf33900-d45e-11e8-862d-4dd437d9c7f0.png">

The same applies to almost every JSON viewer. Either they sort object properties automatically, or they offer an option like the Paw.app

![screen shot 2018-10-20 at 11 57 01 am](https://user-images.githubusercontent.com/623932/47254262-66b6b900-d460-11e8-9dac-f7dba5e6290f.png)

The idea of keeping sorting intact across the board is quite charming, but I fear it's technically impractical.

**Comment by sen542** [comment]
I like fibric's comments on this issue. They read fine :-)

**Comment by wzr1337** [comment]
grrr... convinced :D
