### ISSUE TITLE
promote resource and element keys by one level to remove the "endpoints" key

### ISSUE THREAD

**Issue by wzr1337** [wzr1337/rsi.schema#6]
_Originally posted by @fibric in https://github.com/wzr1337/rsi.schema/pull/1_

> I don't like the endpoints property. In the protocol, we have > defined that everything such as service, resource and
> element is accessible from the URL by its name or id. But the schema doesn't reflect the protocol definition.

**Comment by wzr1337** [comment]
Do we want to promote ?
@fibric suggests to move the `resource` and `elememt` key one level

@sen542 what do you think? Cleaner?

**Comment by sen542** [comment]
I agree. It is cleaner.

**Comment by wzr1337** [comment]
I see the schema looking like that:

```json
{
  "name": "rsi.service.foo",
  "$schema": "rsi#v2",
  "description": "This service lacks description, please fill it in.",
  "resources": {
    "vehicles": {
      "description": "This endpoint holds all registered vehicles",
      "objectModel": {
        "id": {
          "description": "the id",
          "format": "uuid",
          "type": "string"
        },
        "name": {
          "description": "the owners chosen name",
          "type": "string"
        },
        "uri": {
          "description": "object uri",
          "format": "uri",
          "type": "string"
        },
        "VIN": {
          "description": "the vehicle identification number",
          "type": "string"
        }
      },
      "elementAccess": {
        "subscribe": {},
        "get": {}
      },
      "resourceAccess": {
        "subscribe": {},
        "get": {}
      }
    }
  }
}
```
are you OK with `elemetAcsess`and `resourceAccess` for more accurately expressing the purpose of the structure behind?

**Comment by sen542** [comment]
"are you OK with elemetAcsess and resourceAccess for more accurately expressing the purpose of the structure behind?"
Oh yes, I'm. 
As Fibric has sent a comment with smilar meaning we now may close this issue.

**Comment by wzr1337** [comment]
Had an offline dicussion about an even better approach, @fibric will comment on that later..

**Comment by ghost** [comment]
After calling together with @wzr1337, I propose a slightly different solution.

Permissions belong to a certain access method which leads me to the following proposal:

```json
...
    "accessMethods": {
        "subscribe": {
          "parameters": {},
          "usesPermissions": ["vehicleIdentityRead"]
        },
        "get": {
          "parameters": {},
          "usesPermissions": ["vehicleIdentityRead"]
        }
      }
...
```

In the meta-schema, `usesPermission` must be mandatory but should be allowed to hold an empty list to avoid accidentally accessing restricted data.

`accessMethods` belongs to resources and elements likewise. Doing so allows fine granular access model and reduces the need to jump back and forth in the schema when editing manually.
